### ISSUE TITLE
Trim leading/trailing blank lines in cells

### ISSUE THREAD

**Issue by b0o** [SUSTech-data/neopyter#9]
Hi @AbaoFromCUG, thanks for this plugin, I'm enjoying it so far! 

This code in Neovim results in blank lines at the beginning/end of cells in Jupyterlab:

```py
import time

import ipywidgets as widgets
import anywidget
import traitlets
from bqplot import pyplot as plt
from bqplot import LinearScale, Lines, Axis

# %%

print("Hello World")

# %%
```

![2024-08-03_18-06-00_region](https://github.com/user-attachments/assets/b0c2fa2a-3e21-412c-9788-7f799f536eac)

It's nice to use the blank lines in neovim to make the code more readable, but it's unnecessary in Jupyterlab since the cells are already spaced apart from each other. This is how I would prefer for it to look:

![2024-08-03_18-07-23_region](https://github.com/user-attachments/assets/928efd20-90cc-427e-b5a3-afa43880c36d)

I know I can do this, but it looks too disorganized inside Neovim for my liking, especially with more cells:

```py
import time

import ipywidgets as widgets
import anywidget
import traitlets
from bqplot import pyplot as plt
from bqplot import LinearScale, Lines, Axis
# %%
print("Hello World")
# %%
```

In general, I think leading and trailing whitespace should be trimmed when displaying in Jupyterlab.

**Comment by AbaoFromCUG** [comment]
Thanks for your feedback.  Current don't support to trim trailing whitespace, but I am willing to to support it via addition option, how do you think:
```
{
    "SUSTech-data/neopyter",
    opts = {
        -- [WIP] new option
        trim_whitespace=true
    },
}
```

**Comment by b0o** [comment]
I agree, an option would be great.

**Comment by AbaoFromCUG** [comment]
Implement in `v0.2.5`,   by the way, suggestion upgrade `neopyter` via `pip install -U neopyter==0.2.5`, there are some bugfix from `v0.2.3`

`parser.trim_whitespace` default is false, so you need 
```lua
{
    "SUSTech-data/neopyter",
    opts = {
        parser = {
          trim_whitespace=true
        }
    },
}
```
